site_name: "pyncli"


# MkDocs pages configuration. The `<<` operator is sugar added by pydocmd
# that allows you to use an external Markdown file (eg. your project's README)
# in the documentation. The path must be relative to current working directory.
nav:
- Home: index.md
- pyncli.ocs:
  - Simple Ocs API: pyncli/ocs.md
- pyncli.ldap:
  - Simple LDAP API: pyncli/ldap.md

theme:    readthedocs

